### PR TITLE
Scrollbar Changes

### PR DESCRIPTION
**Pull request by AnupeshVerma**
ezgif-2-501b3fb8b7

### CODE REVIEW

**Comment by arunn0909** [comment]
is it on every page or home page only

**Comment by AnupeshVerma** [comment]
I have added code in index.css only

**Comment by AnupeshVerma** [comment]
Now i added the code to all css files
Review deployment at-  https://anupeshverma.github.io/BooksWorld/

**Comment by arunn0909** [comment]
Will merge it after reviewing btw thanks for contributing 😊

**Comment by arunn0909** [comment]
You haven't pushed it i guess

**Comment by AnupeshVerma** [comment]
Now please review

**Comment by arunn0909** [comment]
I haven't reviewed it sorry but I am merging it I hope you have done the great work.

**Pull request merged**
