### PR TITLE
Improvement : Updating the card of Home page [fixes #70]

### LINKED ISSUE #70: Updating the card of Home page
I want that the images will be of full width 
bug1

### PR DESCRIPTION
**Pull request by najeebkp**
Improvement : Updating the card of Home page [fixes #70]

### CODE REVIEW

**Comment by arunn0909** [comment]
Bro can you share screenshots

**Comment by najeebkp** [comment]
Screenshot from 2022-10-06 21-15-26

**Comment by najeebkp** [comment]
@arunn0909  please merge this before any merge conflicts arise.

**Comment by arunn0909** [comment]
Sorry bro I wasn't able to merge your PR because of the merge conflicts. And one more thing does the hover effects still works or you removed it.

**Comment by najeebkp** [comment]
it still works.

**Comment by najeebkp** [comment]
merge conflict resolved !

**Comment by arunn0909** [comment]
Thanks for contributing. @najeebkp

**Pull request merged**
