### PR TITLE
made footer responsive

### PR DESCRIPTION
**Pull request by Chaitanya-087**

### CODE REVIEW

**Comment by arunn0909** [comment]
Thanks for contributing @Chaitanya-087 😊👍

**Comment by arunn0909** [comment]
But I have one question like footer of all the Page are responsive or only the index one 🙄

**Comment by Chaitanya-087** [comment]
yes , since same footer is used and common styles its responsive on all pages

**Comment by arunn0909** [comment]
Thanks and I hope you enoyed working on it and you can raise more issues if you want

**Comment by Chaitanya-087** [comment]
yes

**Pull request merged**
