### PR TITLE
added hover effects to cards in genre section

### PR DESCRIPTION
**Pull request by amansgith**
here is the image of crime card becoming bigger when cursor hovers it and same way other cards will enlarge..

hover

### CODE REVIEW

**Comment by arunn0909** [comment]
bro please resolve the conflicts and before creating any pull request first raise an issue for the same.

**Comment by amansgith** [comment]
i reopened my issue assigned to @amansgith 
and i think the conflict just came because earlier when i did pr no conflict happened

**Comment by amansgith** [comment]
resolved the conflict :)

**Comment by arunn0909** [comment]
ok no issues😉

**Comment by amansgith** [comment]
thank you very much your repo is helping me very much in getting into open source

**Pull request merged**
