### PR TITLE
Added Search Box in every page

### PR DESCRIPTION
**Pull request by AjayMaheshwari23**
If you allow me to change colour of navbar , I can share some images of changed navbar with different styles and I can change if you like any one of those .

### CODE REVIEW

**Comment by arunsingh009** [comment]
Bro this branch has conflict ap isko pehle resolve kro

**Comment by AjayMaheshwari23** [comment]
okay
so, should i close this PR ?

**Comment by arunn0909** [comment]
> okay so, should i close this PR ?

Yes first resolve the conflicts

**Comment by AjayMaheshwari23** [comment]
Okay

**Pull request closed without merging**
