### PR TITLE
Added issue template

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #106 

You can review the code, and kindly inform if there is any requirement of other changes :)

### CODE REVIEW

**Comment by arunn0909** [comment]
Any screenshot of you can provide 🙄

**Comment by zugzwang03** [comment]
How to obtain the screenshot of template?

**Comment by arunn0909** [comment]
Take screenshot then drag and drop here in comment box

**Comment by zugzwang03** [comment]
But wait it is issue template na, where to get its screenshot? It is not visible in the website

**Comment by arunn0909** [comment]
Issue template is for creating issues I guess🙄

**Comment by arunn0909** [comment]
Thanks for contributing 🙏

**Pull request merged**
