### PR TITLE
SignIn page path Updated

### PR DESCRIPTION
**Pull request by moreharsh**
On line 52 of index.html, the path provided for the signIn.html page is updated to the correct path.

### CODE REVIEW

**Comment by arunsingh009** [comment]
I don't think it work after the merge 🙄

**Comment by arunsingh009** [comment]
And one more thing If you want to contribute then first you have to raise an issue regarding it .

**Comment by moreharsh** [comment]
> And one more thing If you want to contribute then first you have to raise an issue regarding it .

Yes sure, I will keep that in mind.
Sorry for the inconvenience.

**Comment by moreharsh** [comment]
> I don't think it work after the merge 🙄

I tried my change on the forked repo and it worked.
The repo name should also be added to the path just to make sure it is working.
It will take some time to update the changes to the GitHub hosted website and one may also need to clear their cache first.

**Comment by moreharsh** [comment]
For testing purpose I have even published the GitHub pages of the forked repo, and you can see over there that the signIn button is redirecting to correct path.
https://moreharsh.github.io/BooksWorld/

**Comment by arunn0909** [comment]
That's awesome bro 😉👍 and thanks for contributing.

**Pull request merged**
