### PR TITLE
change in genre pics

### PR DESCRIPTION
**Pull request by abrknine**
i have change old illustration to real pics

### CODE REVIEW

**Comment by arunn0909** [comment]
Screenshot please 🙏

**Comment by abrknine** [comment]
this screenshot  please review it

**Comment by arunn0909** [comment]
You haven't added the screenshot + it has merge conflicts please resolve it first then only I can merge your PR

**Comment by abrknine** [comment]
Screenshot (371)
  screenshot

**Comment by arunn0909** [comment]
Thanks for contributing 🙏👍

**Pull request merged**
